### ISSUE TITLE
Error during install on Windows 10

### ISSUE THREAD

**Issue by Fred-Vatin** [EdenwareApps/Vimer#1]
Hi,

I downloaded multiple times the installer to be sure is not corrupted. I unblocked it then ran Vimer_1.0.3_win_x64.exe and get this error on Windows 10 22H2 19045.4046.

![image](https://github.com/EdenwareApps/Vimer/assets/22337329/607e08a7-5cf4-41a7-9e03-d0ea54278ec3)

**Comment by EdenwareApps** [comment]
Thank you for letting me know. Now the installer is fixed in the [release 1.0.3](https://github.com/EdenwareApps/Vimer/releases/tag/v1.0.3).
